#!/bin/bash
 
if [ -f ~/.ssh/id_rsa_testlab ]; then
  KEYS="-v $HOME/.ssh/id_rsa_testlab:/root/ssh_keys/id_rsa_testlab"
fi


set -x
docker run --rm -it \
  -v $PWD:/root/f5-openstack-lbaasv2-driver/ \
  $KEYS \
  -e OS_AUTH_URL=${OS_AUTH_URL} \
  -e ICONTROL_HOSTNAME=${ICONTROL_HOSTNAME} \
  -e OS_AUTH_URL_V3=${OS_AUTH_URL_V3} \
  -e OS_TENANT_ID=${OS_TENANT_ID} \
  -e CONTROLLER_HOSTNAME=${CONTROLLER_HOSTNAME} \
    $DOCKER_IMAGE "$@"
