FROM    docker-registry.pdbld.f5net.com/openstack-test/driverbase:19feb7226335
USER    jenkins
RUN     git clone -b stable/mitaka --single-branch https://github.com/F5Networks/neutron-lbaas.git /home/jenkins/neutron-lbaas
RUN     git clone -b mitaka https://github.com/f5devcentral/f5-openstack-ansible.git
